version: '3.0'
services:
# infrastructure for Kafka
  kafka-0:
    image: confluentinc/cp-kafka:7.5.3
    hostname: kafka
    ports:
      - "9092:9092"
    env_file:
      - src/test/resources/kafka/kafka.env



